"""
jira_client.py
---------------
Minimal wrapper around the Jira Cloud REST API (v3) to:
  1. test a connection/credentials
  2. create Epics and Stories from the backlog generated by llm_parser.py

Jira Cloud auth: HTTP Basic Auth using your email + an API token
(create one at https://id.atlassian.com/manage-profile/security/api-tokens)
"""

import requests
from requests.auth import HTTPBasicAuth

HEADERS = {"Accept": "application/json", "Content-Type": "application/json"}


def test_jira_connection(jira_url: str, email: str, token: str):
    """Simple GET to /myself to confirm credentials work."""
    if not all([jira_url, email, token]):
        return False, "Please fill in Jira URL, email, and API token."
    try:
        resp = requests.get(
            f"{jira_url.rstrip('/')}/rest/api/3/myself",
            headers=HEADERS,
            auth=HTTPBasicAuth(email, token),
            timeout=10,
        )
        if resp.status_code == 200:
            name = resp.json().get("displayName", "user")
            return True, f"Connected successfully as {name}."
        return False, f"Connection failed ({resp.status_code}): {resp.text[:200]}"
    except requests.exceptions.RequestException as e:
        return False, f"Connection error: {e}"


def _create_issue(jira_url, auth, project_key, summary, description, issue_type="Story"):
    """Create a single Jira issue. Returns the created issue's key."""
    payload = {
        "fields": {
            "project": {"key": project_key},
            "summary": summary,
            "description": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": description or ""}],
                    }
                ],
            },
            "issuetype": {"name": issue_type},
        }
    }
    resp = requests.post(
        f"{jira_url.rstrip('/')}/rest/api/3/issue",
        headers=HEADERS,
        auth=auth,
        json=payload,
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()["key"]


def push_to_jira(backlog: dict, jira_url: str, email: str, token: str, project_key: str):
    """
    Creates one Jira issue per Epic and one per Story.
    NOTE: Many Jira Cloud "free tier" projects don't have the Epic issue
    type enabled by default for team-managed projects — if Epic creation
    fails, this falls back to creating stories as plain Tasks so the
    demo still works end-to-end. See README troubleshooting section.
    """
    auth = HTTPBasicAuth(email, token)
    results = []

    for epic in backlog.get("epics", []):
        epic_key = None
        try:
            epic_key = _create_issue(
                jira_url, auth, project_key, f"[EPIC] {epic['title']}",
                epic.get("description", ""), issue_type="Epic",
            )
            results.append({"key": epic_key, "summary": f"[EPIC] {epic['title']}"})
        except requests.exceptions.HTTPError:
            pass  # project may not support Epic type — continue with stories

        for story in epic.get("stories", []):
            ac_text = "\n".join(f"- {ac}" for ac in story.get("acceptance_criteria", []))
            full_desc = f"{story.get('description', '')}\n\nAcceptance Criteria:\n{ac_text}"
            story_key = _create_issue(
                jira_url, auth, project_key, story["title"], full_desc, issue_type="Story",
            )
            results.append({"key": story_key, "summary": story["title"]})

    return results
